### ISSUE TITLE
COM swap page not updating

### ISSUE THREAD

**Issue by Pontiac51** [mracko/MSFS-Mobile-Companion-App#23]
It seems the COM swap page is not updated when the frequency is changed in the sim. It works for the direct page.

**Comment by mracko** [comment]
This a known "feature/limitation" of the app. Whatever changes to the frequencies (NAV or COM) you make in the sim will not be automatically updated in the app on the frequency swap page. 

There is a delay of 1 to 2 seconds for data coming from MSFS to the app via the Python Simconnect library. There isn't much I can do about it apart from porting it to native C++. As a result, I've made a workaround by having the frequencies on the swap page updated only once at the start and then use JS to update the values whenever you press a frequency change button. This solves the delay because the frequencies are now changed locally.

You may have noticed that there is a Force Frequency Sync button. This is exactly the reason for it.

**Comment by Pontiac51** [comment]
Thank you very much for that explanation, I did not know that peculiarity.
