### ISSUE TITLE
IP Binding feature request

### ISSUE THREAD

**Issue by cnytech** [mracko/MSFS-Mobile-Companion-App#34]
I have a PC with multiple network cards. I understand this is not a typical setup, but would like to be able to bind the server to a specific subnet.

When I run the server it automatically binds to a subnet that is not on my local network. Because of this I am only able to use the server on localhost, and not on mobile devices.

Would love to see this capability in a future release.

I now find myself using this every time I fly. Thank you for the great FS tool.

**Comment by mracko** [comment]
I understand your issue, but because of my simple network setup, I can't really recreate it.

Have you tried changing line 227 in glass_server.py?
https://github.com/mracko/MSFS-Mobile-Companion-App/blob/d0f7506ddcb87e0a45a5668516682afc949bd887/glass_server.py#L227

You should be able to point it towards the IP address you need. Let me know if this works or if you need help getting the source code to run on your PC (you'll need Python and the Flask library).

**Comment by cnytech** [comment]
> I understand your issue, but because of my simple network setup, I can't really recreate it.
> 
> Have you tried changing line 227 in glass_server.py?
> https://github.com/mracko/MSFS-Mobile-Companion-App/blob/d0f7506ddcb87e0a45a5668516682afc949bd887/glass_server.py#L227
> 
> You should be able to point it towards the IP address you need. Let me know if this works or if you need help getting the source code to run on your PC (you'll need Python and the Flask library).

I ended up fixing it by removing the network. I didn't need it after all for my virtual machine. Thanks for the tip on changing the glass_server.py code though. I'm sure it would have been a good fix for it.

**Comment by mracko** [comment]
That's one way to solve it. :) Thanks for letting me know!
