### ISSUE TITLE
Windows Defender Detects Virus (Trojan:Win32/Spursint.Q!cl) in 1.9.1 release

### ISSUE THREAD

**Issue by juancb** [mracko/MSFS-Mobile-Companion-App#63]
I found this via the official MSFS site and downloaded the 1.9.1 binary archive `MSFS_MCA_v1-9-1.zip` and as soon as I did Windows defender popped up complaining that it contained a virus.

The reported virus is: `Trojan:Win32/Spursint.Q!cl`

You might want to check your build

**Comment by mracko** [comment]
Thanks for letting me know! This is quite strange, however. Could it be that you're running Windows 11?

I always wait a few days after compiling the EXE because I've had false-positive reports with the first couple of versions. I check the file on my PC (MS Defender with the latest 1.353.449.0 definitions) and on [virustotal.com](https://www.virustotal.com/gui/file/3026efdcbc6ee43c04b07036aacd7a89e774a2576d4adcf47758e5569cb1911f?nocache=1) The file is clean (except for SecureAge APEX which I will clarify today - a thing I've already done with a previous version).

Nevertheless I will file a false-positive report to Microsoft. It takes about a half a day for them to clear the file. I'll report back.

**Comment by mracko** [comment]
I've just got a word back from Microsoft. This is what they wrote: 

_We cannot reproduce any detection on the file.  If the detection is still observed, follow the steps below to capture support log files from the system reporting detection._

_On Windows 10, from elevated command prompt, change to directory "%programfiles%\windows defender" and execute mpcmdrun.exe with option GetFiles:_
    _cd "%programfiles%\windows defender"
    mpcmdrun.exe -GetFiles_

_All created log files will be compressed into MPSupportFiles.cab.  Please send us the detected file and MPSupportFiles.cab using https://aka.ms/wdsi.  We will continue the investigation once we receive the support log files._

_Thank you for contacting Microsoft._

Here is a picture from the website:
![image](https://user-images.githubusercontent.com/55148010/140528436-04c46cac-960e-400e-8bd8-7c097fa20675.png)

Please try to rescan it again using the latest definitions and let me know. Thanks!

**Comment by cprgolds** [comment]
FWIW, I am running the new version on Win 11 with Norton.  It runs fine with no indication of any viruses.

**Comment by juancb** [comment]
I updated my windows defender definitions and it's no longer complaining when I try downloading 1.9.1.

Sorry for the wild goose chase.
